on:
  push:
    branches:
      - main

jobs:
  build_css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3
        with:
            ref: main

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: | 
            theme.scss
          destination: | 
            theme.css

      - name: Optimize css using CSSO
        run: |
          npm install -g csso-cli
          mkdir -p ../out
          csso theme.css -o ../out/theme.css
          
      - name: Commit Changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git checkout gh-pages
          rm -rf *
          mv ../out/* . 
          git add --all
          git commit -m 'Push build'
          git push origin gh-pages
