on:
  push:
    branches:
      - main

jobs:
  build_css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3
        with:
            ref: main

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: | 
            theme.scss
          destination: | 
            theme.css

      - name: Optimize css using CSSO
        run: |
          npm install -g csso-cli
          mkdir pages
          csso theme.css -o ./pages/theme.css
          
      - name: Commit Changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add .
          git commit -m 'Push build'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: pages
          branch: gh-pages
