name: Lucord Utils

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    name: Discord Webhook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Run Discord Webhook
      uses: WmeDiscord/BetterWebhooks@main
      with:
        id: ${{ secrets.WEBHOOK_ID }}
        token: ${{ secrets.WEBHOOK_TOKEN }}
        repo-stats: true

  pages:
    name: Move to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3
        with:
            ref: main

      #- name: Compile CSS from SCSS files
        #uses: gha-utilities/sass-build@v0.4.9
        #with:
          #source: | 
            #theme.scss
          #destination: | 
            #theme.css

      - name: Optimize css using CSSO
        run: |
          npm install -g csso-cli
          mkdir -p ../out
          csso theme.css -o ../out/theme.css
          
      - name: Move GH Pages Stuff
        run: |
          mv .github/_includes ../out/_includes
          mv README.md ../out/README.md
          mv CNAME ../out/CNAME
          mv Assets ../out/Assets
          echo ":root {--LU-version:\"$(git rev-parse HEAD | cut -c 1-7)\"}" > ../out/version.css
          
      - name: Commit Changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git rev-parse HEAD | cut -c 1-7 > /tmp/commit
          git checkout --orphan gh-pages
          git rm -rf .
          mv ../out/* . 
          echo ""
          git add --all
          git commit -m 'Push build'
          git push --force origin gh-pages

  screenshot:
    name: Screenshot
    needs: pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
            ref: gh-pages

        uses: actions/checkout@v3
      - name: Create Screenshot
        uses: alexrogalskiy/github-action-screenshots@master
        with:
          url: "https://gibbu.github.io/ThemePreview/?file=https://lucord.wmeluna.com/theme.css"
          name: 'screenshot'
          path: 'Assets'
          width: 1280
          height: 720
          
      - name: Commit
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add --all
          git commit -m 'Update Preview'
          git push