name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript and bundle into asar
        run: pnpm run bundle

      - name: Release
        run: |
          git tag -d v1.0.0 || true
          git push origin --delete v1.0.0 || true
          git tag v1.0.0
          git push origin v1.0.0
          gh release delete v1.0.0 -y || true
          gh release create v1.0.0 -t "v1.0.0" bundle/*
        env:
          GH_TOKEN: ${{ github.token }}
      #- uses: ncipollo/release-action@v1
      #  with:
      #    artifacts: "bundle/*"
      #    makeLatest: true
