name: Screenshot

on:
  workflow_run:
    workflows: ["Move to gh-pages branch"]
    types: [completed]

jobs:
  Screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
            ref: gh-pages

        uses: actions/checkout@v3
      - name: Create Screenshot
        uses: alexrogalskiy/github-action-screenshots@master
        with:
          url: "https://gibbu.github.io/ThemePreview/?file=https://lucord.wmeluna.com/theme.css"
          name: 'screenshot'
          path: 'Assets'
          width: 1280
          height: 720
          
      - name: Commit
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add --all
          git commit -m 'Update Preview'
          git push